# Generated by Django 3.1.6 on 2021-02-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='User',
            new_name='user',
        ),
    ]
